### ISSUE TITLE
你好有个问题问一下

### ISSUE THREAD

**Issue by chenlie449** [yinhui1129754/CppFishingCode#1]
怎么获得捕鱼游戏的无线金币和砖石

**Comment by yinhui1129754** [comment]
逆向找到加金币的call 找到用外置程序调用一下 如果那些游戏没有写反外挂的话
当然可以直接逆向dll文件 网页的话就逆向js文件 
难度都不小

**Comment by yinhui1129754** [comment]
我关闭这个问题了，而且有些开发商会服务器模拟运行 用户就只有一个点击的行为其他都是服务器运算的 意思就是你本地没有加金币的函数方法 没法增加
